name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Since both repos use "master" as the default branch
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository using git
        uses: actions/checkout@v3
        with:
          # No need to specify the repository since it uses the current repo by default
          path: "./"
          fetch-depth: 0
          submodules: "recursive" # This option will checkout submodules

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Specify the Node.js version

      - name: Install dependencies and build the site
        run: |
          cd elvawebs
          pnpm install
          pnpm build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
