name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Since both repos use "master" as the default branch
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository using git
        uses: actions/checkout@v3
        with:
          repository: danielbarillo/danielbarillo.github.io
          path: ./
          # Fetches all history for all tags and branches
          fetch-depth: 0

      - name: Checkout submodule repository using git
        uses: actions/checkout@v3
        with:
          repository: danielbarillo/elvawebs
          path: ./
          # Fetches all history for all tags and branches, ensuring submodule is correctly updated
          fetch-depth: 0
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Specify the Node.js version

      - name: Install dependencies and build the site
        run: |
          cd elvawebs
          pnpm install
          pnpm build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
